/**
 * Detection adapter contract.
 * ---------------------------
 * The app can source parking occupancy from two interchangeable providers:
 *
 *  - "demo"  → DEMO / SIMULATED DATA generated in `src/lib/demo.ts`
 *  - "real"  → a self-hosted YOLO + OpenCV pipeline (see /backend) reached
 *              through the server routes under /api/public/detection/*
 *
 * Both providers return the exact same `DetectionResult` shape, so every
 * screen in the app is agnostic to which one is active.
 */

export type DetectionMode = "demo" | "real";

export type DetectionBox = {
  slot_number: string;
  status: "occupied" | "available" | "unknown";
  confidence: number;
  /** Normalised 0-1 box relative to the source frame. */
  x: number;
  y: number;
  w: number;
  h: number;
};

export type DetectionResult = {
  mode: DetectionMode;
  /** True whenever the numbers are synthetic and must be labelled in the UI. */
  simulated: boolean;
  occupied: number;
  available: number;
  total: number;
  occupancy_percentage: number;
  boxes: DetectionBox[];
  model: string;
  inference_ms: number;
  captured_at: string;
};

export type PipelineHealth = {
  mode: DetectionMode;
  online: boolean;
  endpoint: string | null;
  model: string;
  message: string;
};

export const DETECTION_MODES: { value: DetectionMode; label: string; hint: string }[] = [
  {
    value: "demo",
    label: "DEMO / SIMULATED DATA",
    hint: "Occupancy is generated by the built-in simulator. No camera inference runs.",
  },
  {
    value: "real",
    label: "Real Mode (YOLO + OpenCV)",
    hint: "Frames are posted to the self-hosted Flask detection service for real inference.",
  },
];

export const DETECTION_MODE_STORAGE_KEY = "parksight.detection-mode";
