/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedMyBookingsRouteImport } from './routes/_authenticated/my-bookings'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPredictionRouteImport } from './routes/_authenticated/prediction'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSlotsRouteImport } from './routes/_authenticated/slots'
import { Route as AuthenticatedBookAreaIdRouteImport } from './routes/_authenticated/book.$areaId'
import { Route as ApiPublicDetectionDetectRouteImport } from './routes/api/public/detection/detect'
import { Route as ApiPublicDetectionHealthRouteImport } from './routes/api/public/detection/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyBookingsRoute = AuthenticatedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPredictionRoute = AuthenticatedPredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSlotsRoute = AuthenticatedSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookAreaIdRoute = AuthenticatedBookAreaIdRouteImport.update({
  id: '/book/$areaId',
  path: '/book/$areaId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDetectionDetectRoute =
  ApiPublicDetectionDetectRouteImport.update({
    id: '/api/public/detection/detect',
    path: '/api/public/detection/detect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDetectionHealthRoute =
  ApiPublicDetectionHealthRouteImport.update({
    id: '/api/public/detection/health',
    path: '/api/public/detection/health',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/live': typeof AuthenticatedLiveRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/prediction': typeof AuthenticatedPredictionRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/slots': typeof AuthenticatedSlotsRoute
  '/book/$areaId': typeof AuthenticatedBookAreaIdRoute
  '/api/public/detection/detect': typeof ApiPublicDetectionDetectRoute
  '/api/public/detection/health': typeof ApiPublicDetectionHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/live': typeof AuthenticatedLiveRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/prediction': typeof AuthenticatedPredictionRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/slots': typeof AuthenticatedSlotsRoute
  '/book/$areaId': typeof AuthenticatedBookAreaIdRoute
  '/api/public/detection/detect': typeof ApiPublicDetectionDetectRoute
  '/api/public/detection/health': typeof ApiPublicDetectionHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/prediction': typeof AuthenticatedPredictionRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/slots': typeof AuthenticatedSlotsRoute
  '/_authenticated/book/$areaId': typeof AuthenticatedBookAreaIdRoute
  '/api/public/detection/detect': typeof ApiPublicDetectionDetectRoute
  '/api/public/detection/health': typeof ApiPublicDetectionHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/analytics'
    | '/areas'
    | '/bookings'
    | '/dashboard'
    | '/live'
    | '/my-bookings'
    | '/payments'
    | '/prediction'
    | '/reports'
    | '/search'
    | '/settings'
    | '/slots'
    | '/book/$areaId'
    | '/api/public/detection/detect'
    | '/api/public/detection/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/analytics'
    | '/areas'
    | '/bookings'
    | '/dashboard'
    | '/live'
    | '/my-bookings'
    | '/payments'
    | '/prediction'
    | '/reports'
    | '/search'
    | '/settings'
    | '/slots'
    | '/book/$areaId'
    | '/api/public/detection/detect'
    | '/api/public/detection/health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/areas'
    | '/_authenticated/bookings'
    | '/_authenticated/dashboard'
    | '/_authenticated/live'
    | '/_authenticated/my-bookings'
    | '/_authenticated/payments'
    | '/_authenticated/prediction'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/slots'
    | '/_authenticated/book/$areaId'
    | '/api/public/detection/detect'
    | '/api/public/detection/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicDetectionDetectRoute: typeof ApiPublicDetectionDetectRoute
  ApiPublicDetectionHealthRoute: typeof ApiPublicDetectionHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-bookings': {
      id: '/_authenticated/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof AuthenticatedMyBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prediction': {
      id: '/_authenticated/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof AuthenticatedPredictionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slots': {
      id: '/_authenticated/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof AuthenticatedSlotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$areaId': {
      id: '/_authenticated/book/$areaId'
      path: '/book/$areaId'
      fullPath: '/book/$areaId'
      preLoaderRoute: typeof AuthenticatedBookAreaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/detection/detect': {
      id: '/api/public/detection/detect'
      path: '/api/public/detection/detect'
      fullPath: '/api/public/detection/detect'
      preLoaderRoute: typeof ApiPublicDetectionDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/detection/health': {
      id: '/api/public/detection/health'
      path: '/api/public/detection/health'
      fullPath: '/api/public/detection/health'
      preLoaderRoute: typeof ApiPublicDetectionHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMyBookingsRoute: typeof AuthenticatedMyBookingsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPredictionRoute: typeof AuthenticatedPredictionRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSlotsRoute: typeof AuthenticatedSlotsRoute
  AuthenticatedBookAreaIdRoute: typeof AuthenticatedBookAreaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMyBookingsRoute: AuthenticatedMyBookingsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPredictionRoute: AuthenticatedPredictionRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSlotsRoute: AuthenticatedSlotsRoute,
  AuthenticatedBookAreaIdRoute: AuthenticatedBookAreaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicDetectionDetectRoute: ApiPublicDetectionDetectRoute,
  ApiPublicDetectionHealthRoute: ApiPublicDetectionHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
